class ProfileStorage:
    """Сохранение/загрузка наборов выбранных файлов в JSON."""
    def save(self, name: str, rel_paths: list[str]): ...
    def load(self, name: str) -> list[str]: ...
    def list_profiles(self) -> list[str]: ...